### ISSUE TITLE
Deployment target for 10.10

### ISSUE THREAD

**Issue by oxeron** [s1ddok/CCProjectGenerator#2]
You set the deployment target for 10.11 but everything seems to work for 10.10 

You may want to allow 10.10 for your application ?

**Comment by s1ddok** [comment]
It is just due to I didn't fix any default XCode settings yet, mostly because I don't have 10.10 to test it. Will fix it shortly

**Comment by oxeron** [comment]
No problem, if you need 10.10 testing, just tell me
