### ISSUE TITLE
Error when compiling test project

### ISSUE THREAD

**Issue by oxeron** [s1ddok/CCProjectGenerator#3]
Maybe you dont want us to report bugs related to cocos2d in this project but I just created a test project (objC, with chipmunks and Spritebuilder support) and got an error when compiling:

/Users/opierre/Desktop/test/Source/libs/cocos2d-ext/CCBReader/CCAnimationManager.m:233:37: Use of undeclared identifier 'CCLightNode'

I also wanted to ask you how you will keep this project generator synced with cocos2d-objC ? now you have cocos2d shipped inside your app, do you plan to download the last version from github maybe ?

**Comment by s1ddok** [comment]
Ugh, It seems like I forgot to update CCBReader extension to latest one from 3.5 repo. Will be fixed shortly

**Comment by s1ddok** [comment]
Problem should be now gone.
