### ISSUE TITLE
Can't open project in Spritebuilder

### ISSUE THREAD

**Issue by oxeron** [s1ddok/CCProjectGenerator#4]
Generated project cannot be opened in SpriteBuilder, the name of the project should be PROJECTNAME.spritebuilder and some files are missing

Maybe I'll merge your tool inside my SpriteBuilder fork ...

**Comment by s1ddok** [comment]
Doh, I was checking this, something went wrong again >.< Will take a look on this.

Merging is not a good idea bc some people dont wanna use SB, and it is generally hated, even though it has a big fanbase too. So cocos2d must be a tool which can be used without SB at all.

**Comment by oxeron** [comment]
True

**Comment by s1ddok** [comment]
Just tested it on my laptop with SB from Appstore, everythings seems just fine.

**Comment by oxeron** [comment]
Yes it works

I was confused by the fart that the Xcode project when compiling did not have the same result that the SB project by default

**Comment by s1ddok** [comment]
I'm not sure what you mean

**Comment by s1ddok** [comment]
Closed due to we can't reproduce it for now.

**Comment by oxeron** [comment]
It's ok, my version of SB is still using an old openProject code, and it can't open .ccbproj files now
Sorry for the noise
