### ISSUE TITLE
Error for Mac target

### ISSUE THREAD

**Issue by oxeron** [s1ddok/CCProjectGenerator#5]
I build an empty project for MAC generated by CCProjectGenerator and got this error:

![capture d ecran 2016-03-09 a 09 42 06](https://cloud.githubusercontent.com/assets/587942/13629747/72b2b9f0-e5db-11e5-9a96-c796507d3475.png)

The header search path for mac target is missing cocos directories

**Comment by s1ddok** [comment]
Hmm seems like we need to wrap that import with `if CC_Packages`, will see that as soon as I get to my laptop

**Comment by s1ddok** [comment]
seems to be fixed
