### ISSUE TITLE
No tile maps?

### ISSUE THREAD

**Issue by technicallyerik** [s1ddok/CCProjectGenerator#8]
I used this to generate a project, and there doesn't seem to be any "CCTiledMap.h" class in my project  referenced by http://cocos2d.spritebuilder.com/docs/api/Classes/CCTiledMap.html

**Comment by s1ddok** [comment]
Default tilemap code is no more a part of a core engine. It is still available as extension and can be found in main repo. But also is kind of deprecated. 

The recommended solution now is to use such tools like TileMapKit or something. However the default is still quite good and can be used for most games.
